### PR TITLE
cross-browsers fixes for "get new codes here"

### LINKED ISSUE #54: New codes here browser problems
- [x] "DOWNLOAD" doesn't work on Edge/Win10
- [x] Rendering issue on FF/[macOS|Linux]: only 4 codes show/column even though there were 5 in source (the overflow: hidden on the supporting-text class is cutting them off)
- [x] IE11/Win10, renders codes in a single column always, printing and data: url don't work

introduced in https://github.com/silinternational/simplesamlphp-module-material/releases/tag/5.2.0

### LINKED ISSUE #55: Consistent language
Change the language of "account" to "identity account"

### PR DESCRIPTION
**Pull request by wcjr**
resolves #54 

in addition, resolves #55

### CODE REVIEW

File: themes/material/mfa/new-backup-codes.php [hunk 1]
```diff
@@ -4,8 +4,32 @@
...
+                disableDownload();
+            } else if (bowser.msedge) {
+                disableDownload();
+            }
+        }
+
+        function disablePrint() {
+            document.querySelector('button#print').disabled = true;
+            document.querySelector('button#print').classList.add('not-allowed');
+            document.querySelector('button#print').title = '<?= $this->t('{material:mfa:unsupported}') ?>'
```
Comment (forevermatt) [inline themes/material/mfa/new-backup-codes.php]: Since we're inserted a raw string into JavaScript, we probably want to change this...
```js
document.querySelector('button#print').title = '<?= $this->t('{material:mfa:unsupported}') ?>'
```
... to this...
```js
document.querySelector('button#print').title = <?= json_encode($this->t('{material:mfa:unsupported}')) ?>;
```
... so that apostrophes won't break the JS syntax.

File: themes/material/mfa/new-backup-codes.php [hunk 2]
```diff
@@ -4,8 +4,32 @@
...
+        function disablePrint() {
+            document.querySelector('button#print').disabled = true;
+            document.querySelector('button#print').classList.add('not-allowed');
+            document.querySelector('button#print').title = '<?= $this->t('{material:mfa:unsupported}') ?>'            
+        }
+
+        function disableDownload() {
+            document.querySelector('a[download]').href = '';
+            document.querySelector('a[download]').classList.add('mdl-button--disabled', 'not-allowed');
+            document.querySelector('a[download]').title = '<?= $this->t('{material:mfa:unsupported}') ?>'
```
Comment (forevermatt) [inline themes/material/mfa/new-backup-codes.php]: Same here (re: json_encode)

File: themes/material/mfa/new-backup-codes.php (hunk 1 above)
Comment (wcjr) [reply themes/material/mfa/new-backup-codes.php]: fixed those, thanks!

File: themes/material/mfa/new-backup-codes.php (hunk 2 above)
Comment (wcjr) [reply themes/material/mfa/new-backup-codes.php]: same here (re: your feedback)
